/** Har bir video qo'llanmasiga qo'shimcha batafsil punktlar */
export const videoGuideExtras: Record<string, string[]> = {
  "p1-1": [
    "Bitcoin whitepaper 2008-yilda e'lon qilindi — 'peer-to-peer electronic cash' g'oyasi.",
    "Uchta asosiy muammo hal qiladi: ikki marta sarflash, ishonch, markazlashtirish.",
    "Ochiq manba kod — har kim tarmoq qoidalarini tekshirishi mumkin.",
    "Bitcoin manzili 26–35 belgidan iborat bo'lishi mumkin (Base58Check).",
    "Birinchi real tranzaksiya: 2010-yilda 10 000 BTC bilan pizza sotib olingan.",
    "O'rganuvchi uchun maslahat: avval Bitcoin nima EMAS (bank, kompaniya) deganini tushuning.",
  ],
  "p1-2": [
    "Tranzaksiya imzosi shaxsiy kalit bilan yaratiladi — matematik isbot.",
    "Blok vaqti o'rtacha ~10 daqiqa — Bitcoin tarmog'ida.",
    "Mining qiyinligi har 2016 blokda avtomatik sozlanadi.",
    "Komissiya (fee) tranzaksiya tezligiga ta'sir qiladi — mempool band bo'lganda oshadi.",
    "UTXO modeli: har bir chiqish keyingi kirish bo'ladi — hisob qoldig'i emas.",
    "Narx grafigini kuzatish ta'lim uchun foydali, lekin bashorat emas — DYOR.",
  ],
  "p1-3": [
    "Double coincidence of wants — barterning asosiy muammosi.",
    "Qog'oz pul avvalo banklar tomonidan chiqarilgan — markaziy emissiya.",
    "Elektron pul bank balansidagi raqam — fizik naqd emas.",
    "Kripto aktivlar davlat chegarasidan mustaqil uzatilishi mumkin.",
    "So'm (UZS) — O'zbekiston milliy fiat valyutasi, Markaziy bank emitenti.",
    "Pul sifatida qabul qilish (acceptance) ijtimoiy kelishuv va qonun bilan mustahkamlanadi.",
  ],
  "p1-4": [
    "Hash funksiyasi — kirishni o'zgartirsangiz, chiqish butunlay boshqacha bo'ladi.",
    "Merkle daraxti — minglab tranzaksiyani samarali tekshirish imkonini beradi.",
    "51% hujum — nazariy xavf: tarmoq quvvatining yarmidan ko'pini boshqarish.",
    "Bitcoin blok hajmi cheklangan — muntazam yangilanishlar (SegWit va b.) qo'shildi.",
    "Smart-kontrakt Bitcoinda cheklangan; Ethereum kengaytirilgan imkoniyat beradi.",
    "Blockchain shaffofligi: har kim explorer orqali tranzaksiyalarni ko'ra oladi.",
  ],
  "p1-5": [
    "CEX (markazlashtirilgan birja) — buyurtmalar kitobi va KYC bilan ishlaydi.",
    "DEX (markazsiz birja) — smart-kontrakt orqali peer-to-peer savdo.",
    "Mining pool — kichik minerlar kuchini birlashtirib mukofot bo'lishadi.",
    "Lightning Network — Bitcoin uchun tez va arzon kichik to'lovlar qatlami.",
    "On-chain vs off-chain: asosiy zanjir xavfsiz, lekin sekinroq bo'lishi mumkin.",
    "Ekosistemada hamkorlik: hamyon ishlab chiquvchilari, auditorlar, media, ta'lim platformalari.",
  ],
  "p1-6": [
    "Public key → manzil; private key → imzo va egalik huquqi.",
    "BIP-39 standarti — 2048 so'zdan iborat seed lug'ati.",
    "Hardware wallet chipida kalit saqlanadi — kompyuterdan ajratilgan.",
    "SIM-swap hujumi: telefon raqamini o'g'irlash orqali 2FA aylanishini aylanish.",
    "Rasmiy dastur faqat App Store / Google Play yoki ishlab chiquvchi saytidan.",
    "O'zbekiston: NAPP litsenziyali provayderlar ro'yxatini tekshiring — qonuniy yo'l.",
  ],

  "p2-1": [
    "Hisob birligi: narxlar so'm, dollar yoki BTC da ifodalanadi.",
    "Qiymat saqlash: pul kelajakdagi xarid kuchini saqlashi kerak.",
    "Kredit puli — bank tomonidan yaratilgan, zaxira talab qiladi.",
    "Quantitative easing — markaziy bank aktiv sotib olib pul massasini oshirishi.",
    "Pul tezligi — iqtisodiyotda pul aylanma tezligi ko'rsatkichi.",
    "Kripto yangi bosqich: programmalashtirilgan pul va CBDC ham muhokama qilinmoqda.",
  ],
  "p2-2": [
    "Censorship resistance — tranzaksiyani bir shaxs to'xtata olmaydi (nazariy).",
    "Bitcoin Lightning va boshqa L2 yechimlar kundalik to'lovni yengillashtiradi.",
    "El Salvador 2021-yilda BTC ni qonuniy to'lov vositasi qildi — tarixiy misol.",
    "Regulyatorlar turli mamlakatlarda BTC ni aktiv, tovar yoki pul deb ko'radi.",
    "Network effect: ko'p foydalanuvchi — ko'p ishonch va likvidlik.",
    "Bitcoin energiya sarfi muhokama mavzusi — qayta tiklanuvchi manbalar ulushi oshmoqda.",
  ],
  "p2-3": [
    "CPI (iste'mol narxlari indeksi) — inflyatsiyani o'lchashda ishlatiladi.",
    "Deflyatsiya — narxlar pasayishi; ham ijobiy, ham salbiy oqibatlari bor.",
    "Stagflyatsiya — inflyatsiya + iqtisodiy o'sish to'xtashi.",
    "Real foiz stavkasi = nominal foiz − inflyatsiya.",
    "Bitcoin taklifi bashorat qilinadigan — halving jadvali ochiq.",
    "O'zbekistonda inflyatsiyani Markaziy bank monitoring qiladi — yangiliklarni kuzating.",
  ],
  "p2-4": [
    "IPO — kompaniya birinchi marta aksiyalarni ommaviy sotadi.",
    "ETF — bir nechta aktivdan iborat fond; Bitcoin ETF institutsional kirishni osonlashtirdi.",
    "Bear market — uzoq muddatli pasayish; bull market — o'sish davri.",
    "Market cap = narx × aylanmadagi miqdor — loyiha hajmini baholash.",
    "Kripto loyihalarining whitepaper va tokenomics ini o'qing — fundamental tahlil.",
    "Scam loyihalar ko'pincha jamoasiz, noaniq maqsadsiz va 'guaranteed profit' va'da qiladi.",
  ],
  "p2-5": [
    "Order book — sotib olish va sotish buyurtmalari ro'yxati.",
    "Slippage — katta buyurtmada kutilgan narxdan farqli bajarilish.",
    "APY vs APR — foiz hisoblashda murakkablik; DeFi da muhim.",
    "Yield farming — likvidlik berib mukofot olish; smart-kontrakt xavfi bor.",
    "Oracle — off-chain ma'lumotni blockchain ga olib kiradi (narx, ob-havo).",
    "Rug pull — loyiha egalari likvidlikni olib qochishi; DYOR va ehtiyot.",
  ],
  "p2-6": [
    "Risk tolerance — siz qancha tebranishga chidashingiz.",
    "Stop-loss — zararni cheklash buyurtmasi; yangi boshlovchilar uchun foydali.",
    "Take-profit — maqsadli narxda sotish; reja bilan ishlash.",
    "Portfolio rebalancing — aktivlar nisbatini vaqti-vaqti bilan tuzatish.",
    "Tax-loss harvesting — soliq maqsadida zarar realizatsiyasi (qonunlarga qarab).",
    "Ta'lim investitsiyadan muhimroq — bilmasdan kiritilgan pul tez yo'qolishi mumkin.",
  ],

  "p4-1": [
    "Time preference — bugun sarflash yoki ertaga tejash tanlovi.",
    "Likvidlik — aktivni tez va arzon sotish imkoniyati.",
    "Oltin ETF — fizik oltinsiz ham oltin investitsiyasi mumkin.",
    "Real estate — ko'chmas mulk ham xazina, lekin likvidligi pastroq.",
    "Emergency fund — 3–6 oylik xarajat zaxirasi avvalo naqd yoki barqaror aktivda.",
    "Bitcoin uzoq muddatli (5–10 yil) strategiya bilan ko'proq muhokama qilinadi.",
  ],
  "p4-2": [
    "Stock-to-flow modeli — taklif va chiqarish nisbati (bahsli model, ta'lim uchun).",
    "Custody xizmatlari — institutlar uchun professional saqlash.",
    "Bitcoin ETF (2024 AQSh) — an'anaviy investorlar uchun kirish yo'li ochildi.",
    "Correlation — BTC ba'zan aksiyalar bilan, ba'zan mustaqil harakatlanadi.",
    "HODL madaniyati — uzoq muddat saqlash va tez sotmaslik falsafasi.",
    "Dollar cost averaging xazina yig'ishda ham ishlaydi — emotsiyani kamaytiradi.",
  ],
  "p4-3": [
    "Oltin saqlash: seyf, bank qutisi, sertifikat — xarajat va xavf.",
    "Bitcoin uzatish: 10 daqiqadan soatgacha — tarmoq yukiga bog'liq.",
    "CBDC (raqamli markaziy bank puli) — davlat nazoratidagi raqamli so'm kelajagi.",
    "Inflation hedge narrativi — ikkala aktiv ham sinovdan o'tkazilmoqda.",
    "Generatsiya farqi: yoshlar raqamli, kattalar fizik oltin afzal ko'rishi mumkin.",
    "Hech bir aktiv 100% xavfsiz emas — diversifikatsiya tamoyilini unutmang.",
  ],
  "p4-4": [
    "Support — narx pastda to'xtab qoladigan zona; resistance — yuqoridagi to'siq.",
    "RSI, MACD — mashhur indikatorlar; signal emas, yordamchi vosita.",
    "Whale — katta miqdordagi BTC egasi; harakatlari bozorga ta'sir qilishi mumkin.",
    "FUD (fear, uncertainty, doubt) — salbiy mish-mishlar; faktlarni tekshiring.",
    "FOMO va FUD ikkalasi ham xato qarorga olib kelishi mumkin.",
    "On-chain: HODL waves, exchange in/outflow — ta'lim maqsadida o'rganish mumkin.",
  ],
  "p4-5": [
    "Fed (AQSh) foiz qarorlari butun dunyo bozorlariga ta'sir qiladi.",
    "DXY — dollar indeksi; kuchli dollar ko'pincha riskli aktivlarga salbiy.",
    "Stagflyatsiya davrida investorlar xatti-harakati murakkablashadi.",
    "Bitcoin halving va makro voqealar ba'zan bir vaqtda bo'ladi — tahlil qiyinlashadi.",
    "O'zbekiston iqtisodiyoti ham global zanjirga bog'liq — eksport, import, valyuta.",
    "Yangiliklar kalendari: CPI, ish joylari, FOMC — kutilmagan tebranishlar bo'lishi mumkin.",
  ],
  "p4-6": [
    "Paper wallet — qog'ozda kalit (eskirgan usul, ehtiyot bilan).",
    "Shamir backup — metall plastinkada seed — olov va suvga chidamli.",
    "Social recovery — ishonchli shaxslar orqali tiklash (yangi yondashuvlar).",
    "Inheritance planning — meros rejasi: oila a'zolari kalitlarni bilsin (xavfsiz usulda).",
    "Birja proof-of-reserve audit — mablag' yetarlimi tekshiruvi.",
    "Parol menejeri + 2FA + sovuq hamyon — uch qavatli himoya modeli.",
  ],

  "p10-1": [
    "NAPP — O'zbekiston Respublikasi Prezidenti huzuridagi milliy agentlik.",
    "Virtual aktivlar to'g'risidagi qonun loyihalari va farmonlarni kuzatib boring.",
    "AML (anti-money laundering) — shubhali tranzaksiyalarni aniqlash qoidalari.",
    "KYC darajalari: telefon, pasport, manzil tasdiqlash — platformaga qarab.",
    "Qora ro'yxat va sanktsiyalar — ba'zi manzillar va mamlakatlar cheklangan.",
    "Ta'lim maqsadi: qonuniy yo'l uzoq muddatda eng xavfsiz strategiya.",
  ],
  "p10-2": [
    "SWIFT va bank o'tkazmalari — fiat chiqarishning an'anaviy yo'li.",
    "Stablecoin orqali konvertatsiya — platforma qoidalariga qarab.",
    "Withdrawal limit — kunlik/oylik yechish cheklovi; oldindan bilib oling.",
    "Maker/taker komissiya — birja tariflarini solishtiring.",
    "Proof of address — kommunal to'lov yoki bank ko'chirmasi talab qilinishi mumkin.",
    "Mijozlarni qo'llab-quvvatlash — muammo bo'lsa faqat rasmiy kanal orqali murojaat.",
  ],
  "p10-3": [
    "FIFO, LIFO — foyda hisoblash usullari (soliq qonunlariga qarab).",
    "Mining daromadi ham soliq obyekti bo'lishi mumkin — mamlakat qoidalariga qarab.",
    "Airdrop va staking mukofoti — daromad sifatida qayd etilishi mumkin.",
    "Excel yoki maxsus dastur — tranzaksiya jurnalini yuritish.",
    "Soliq deklaratsiyasi: o'z vaqtida topshirish — jarima va foizdan qochish.",
    "Qonuniy ravishda to'lash — bank va davlat oldida ishonchli tarix.",
  ],
  "p10-4": [
    "Hot wallet — birja onlayn saqlaydi; sovuq zaxira — offline qismi.",
    "Withdrawal whitelist — faqat oldindan ro'yxatdan o'tkazilgan manzilga yechish.",
    "Anti-phishing kodi — birja xatlarida maxsus so'z ko'rsatiladi.",
    "API kalit — bot uchun; faqat kerakli ruxsatlar, IP cheklovi.",
    "Email xavfsizligi — birja akkaunti uchun alohida, kuchli parol.",
    "Kichik summani birjada, asosiy mablag'ni sovuq hamyonda — amaliy qoida.",
  ],
  "p10-5": [
    "Loss aversion — yo'qotish og'riqliroq his qilinadi — psixologik tuzoqqa olib keladi.",
    "Confirmation bias — faqat o'z fikrini tasdiqlovchi yangiliklarni qidirish.",
    "Sunk cost fallacy — 'allaqachon ko'p kiritdim' deb xato davom ettirish.",
    "Trading jurnal — har bir qarorni yozib, xatolardan o'rganish.",
    "Uyqu va dam olish — charchagan holda qaror qabul qilmang.",
    "Maqsad: emotsiyani boshqarish — tizimli ta'lim va reja bilan mumkin.",
  ],
  "p10-6": [
    "Pump and dump — narx sun'iy ko'tariladi, keyin tashlab ketiladi.",
    "Rug pull — DeFi loyihasida likvidlik o'g'irlash.",
    "Fake support — Telegramda 'admin' nomi bilan seed so'rash.",
    "Clipboard malware — manzilni almashtiradi; yuborishdan oldin tekshiring.",
    "Too good to be true — agar juda yaxshi bo'lsa, ehtimol scam.",
    "Doimiy o'rganish: kripto  tez o'zgaradi — bugungi xavf ertaga yangi shakl olishi mumkin.",
  ],
};
