import type { BuildingDef } from "./types";

/** Faqat maydon ichidagi kompakt xarita */
export const MAP_WIDTH = 26;
export const MAP_HEIGHT = 18;
export const TILE_SIZE = 32;

/** O'yinchi va obyektlar chegarasi (piksel) */
export const FIELD_BOUNDS = {
  minX: 56,
  minY: 56,
  maxX: MAP_WIDTH * TILE_SIZE - 56,
  maxY: MAP_HEIGHT * TILE_SIZE - 56,
};

/** Barcha binolar maydon ichida — 3 qator */
export const BUILDINGS: BuildingDef[] = [
  {
    id: "scam_detective",
    name: "Scam Dedektiv Idorasi",
    nameUz: "Crypto Shop",
    description: "Firibgarliklarni aniqlang",
    tileX: 3,
    tileY: 2,
    width: 4,
    height: 3,
    color: 0x3a2a1a,
    accentColor: 0xff8c42,
    alwaysOpen: true,
    minimapIcon: "🚐",
    zone: "scam_detective",
  },
  {
    id: "bitcoin_mine",
    name: "Bitcoin Minasi",
    nameUz: "Kripto Vault",
    description: "Hash mining simulyatori",
    tileX: 11,
    tileY: 2,
    width: 4,
    height: 3,
    color: 0x1a3a2a,
    accentColor: 0x00ff88,
    requiredCourse: "bitcoin_basics",
    minimapIcon: "⛏️",
    zone: "bitcoin_mine",
  },
  {
    id: "guild_hall",
    name: "Guild Xonasi",
    nameUz: "Ofis",
    description: "Guild a'zolari uchun",
    tileX: 19,
    tileY: 2,
    width: 4,
    height: 3,
    color: 0x4a2a5a,
    accentColor: 0xda70d6,
    requiresGuild: true,
    minimapIcon: "⚔️",
    zone: "guild_hall",
  },
  {
    id: "napp_office",
    name: "NAPP Ofisi",
    nameUz: "NAPP Bank",
    description: "VASP litsenziya simulyatori",
    tileX: 3,
    tileY: 7,
    width: 4,
    height: 4,
    color: 0x1a4a2a,
    accentColor: 0x00a86b,
    requiredCourse: "napp_law",
    minimapIcon: "🏢",
    zone: "napp_office",
  },
  {
    id: "city_square",
    name: "Shahar Maydoni",
    nameUz: "Maktab",
    description: "Markaziy maydon",
    tileX: 10,
    tileY: 6,
    width: 6,
    height: 5,
    color: 0x2a2a3a,
    accentColor: 0xf4b942,
    alwaysOpen: true,
    minimapIcon: "🏛️",
    zone: "city_square",
  },
  {
    id: "ethereum_lab",
    name: "Ethereum Laboratoriyasi",
    nameUz: "Bank",
    description: "Smart kontrakt quruvchi",
    tileX: 19,
    tileY: 7,
    width: 4,
    height: 4,
    color: 0x1a2a4a,
    accentColor: 0x627eea,
    requiredCourse: "ethereum_basics",
    minimapIcon: "🏦",
    zone: "ethereum_lab",
  },
  {
    id: "marketplace",
    name: "Bozor Maydoni",
    nameUz: "Bitcoin Shop",
    description: "Avatar kostyumlari",
    tileX: 3,
    tileY: 13,
    width: 4,
    height: 4,
    color: 0x3a3a1a,
    accentColor: 0xffd700,
    alwaysOpen: true,
    minimapIcon: "🛒",
    zone: "marketplace",
  },
  {
    id: "trading_center",
    name: "Trading Markazi",
    nameUz: "Do'kon",
    description: "Virtual savdo",
    tileX: 10,
    tileY: 13,
    width: 5,
    height: 4,
    color: 0x2a1a3a,
    accentColor: 0xff6b35,
    requiredCourse: "trading_basics",
    minimapIcon: "🏪",
    zone: "trading_center",
  },
  {
    id: "defi_pool",
    name: "DeFi Hovuzi",
    nameUz: "Uy",
    description: "Likvidlik hovuzi",
    tileX: 19,
    tileY: 13,
    width: 4,
    height: 4,
    color: 0x0a3a2a,
    accentColor: 0x00d68f,
    requiredCourse: "defi_basics",
    minimapIcon: "🏠",
    zone: "defi_pool",
  },
  {
    id: "secret_library",
    name: "Sirli Kutubxona",
    nameUz: "Bank 2",
    description: "Yashirin xazina",
    tileX: 22,
    tileY: 10,
    width: 3,
    height: 2,
    color: 0x1a1a2a,
    accentColor: 0x9b59b6,
    requiresLevel: 10,
    minimapIcon: "📚",
    zone: "secret_library",
  },
];

export const COURSE_LABELS: Record<string, string> = {
  bitcoin_basics: "Bitcoin Asoslari",
  ethereum_basics: "Ethereum Asoslari",
  napp_law: "NAPP Qonunchiligi",
  trading_basics: "Trading Asoslari",
  defi_basics: "DeFi Asoslari",
};

export function getBuildingById(id: string) {
  return BUILDINGS.find((b) => b.id === id);
}
